### ISSUE TITLE
Add CalcMod?

### ISSUE THREAD

**Issue by shadeydo** [qwert123451234/Star-Optimized#1]
calcmod is a calculator in the chat with shorcuts designed to make minecraft life easier. just a general QoL mod that might fit star optimized! heres a link to the mod: [https://modrinth.com/mod/calcmod](https://modrinth.com/mod/calcmod)

**Comment by MrPup-minecraftkus** [comment]
I will think about it, maybe I will add this mod in the next version and see how it will lead on the assembly, if it crashes or lags, I will remove it.

**Comment by MrPup-minecraftkus** [comment]
I'm sorry, but I looked at the Starlight mod and it is also responsible for star optimization, and I don't see the point in adding two star optimization mods

**Comment by shadeydo** [comment]
umm calcmod isnt an optimization mod?

**Comment by shadeydo** [comment]
umm calcmod isnt an optimization mod?

**Comment by qwert123451234** [comment]
Your mod is partially optimizing, but I don't see the point of adding it because there is already a mod that optimizes stars (Starlight)

**Comment by qwert123451234** [comment]
> umm calcmod isnt an optimization mod?

Your mod is partially optimizing, but I don't see the point of adding it because there is already a mod that optimizes stars (Starlight)

**Comment by MrPup-minecraftkus** [comment]
Your mod is partially optimizing, I will add your mod to version 1.2.0beta5, also noticed that your mod on Curseforge is maintained by another person or is it you?

**Comment by shadeydo** [comment]
It is the other developer of the mod.
